1. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [ ]:
import numpy as np

list = [12.23, 13.32, 100, 36.32]
my_list = np.array(list)
my_list


array([ 12.23,  13.32, 100.  ,  36.32])

2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:

[[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [6]:
random_array = np.arange(2,11).reshape(3,3)
random_array

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [10]:
arr = np.zeros(10)
arr[5] = 11
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

4.Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [12]:
new_array = np.arange(12,38)
new_array

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

Write a NumPy program to convert an array to a floating type.

Sample output:

Original array [1, 2, 3, 4]

In [ ]:
list = [1,2,3,4]
arr = np.array(list)
new_arr = arr.astype(float)


dtype('float64')

Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

Sample Array [0, 12, 45.21, 34, 99.91] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

Expected Output:

Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]

In [19]:
celsius_arr = np.array([0, 12, 45.21, 34, 99.91])
faranheit_arr = celsius_arr * 9/5 + 32
faranheit_arr


array([ 32.   ,  53.6  , 113.378,  93.2  , 211.838])

Write a NumPy program to append values to the end of an array.

Expected Output:

Original array: [10, 20, 30]

After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [21]:
original_array = np.array([10,20,30])
new_values = [40,50,60,70,80,90]
appended_array = np.append(original_array,new_values)
appended_array

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

8.Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

In [31]:
random = np.random.rand(10)
mean = np.mean(random)
median = np.median(random)
std = np.std(random)    

9.Create a 10x10 array with random values and find the minimum and maximum values.

In [40]:
array = np.random.rand(10,10)
minimum = np.min(array)
maximum = np.max(array)

Create a 3x3x3 array with random values.



In [41]:
array = np.random.rand(3,3,3)
array

array([[[0.08788634, 0.44783594, 0.46600288],
        [0.57070253, 0.42975711, 0.43566654],
        [0.76950737, 0.0564556 , 0.40130805]],

       [[0.4669456 , 0.57524396, 0.4296825 ],
        [0.94150948, 0.05060773, 0.32016587],
        [0.82769879, 0.74859659, 0.05918966]],

       [[0.04813905, 0.71077128, 0.76815712],
        [0.49711656, 0.62593112, 0.42328177],
        [0.65152878, 0.68832438, 0.44061509]]])